### ISSUE TITLE
add warning to model  wrt841n(d) v9 

### ISSUE THREAD

**Issue by research7** [freifunk-berlin/nipap-wizard#30]
Flashing of this model succeeds, BUT leaves no memory for configuration see [https://github.com/freifunk-berlin/firmware/issues/191#issuecomment-68630029 freifunk-firmware].

So it might be helpful to warn users before downloading and flashing until the mentioned issue is resolved.
Thanks.

**Comment by research7** [comment]
This router model should be removed from the freifunk config database, b/c is does not have enough memory to deal with the freifunk firmware properly.
(see reference above).

**Comment by cholin** [comment]
@sarumpaet  added a warning note to the router list with #31. I think this is sufficient for the moment and therefor I close this issue. Feel free to reopen!

**Comment by research7** [comment]
Yeah, I think this is a sufficient warning. 
Thanks!
